<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-RabbitMqApp.WorkerService-bc970cdc-d31c-4b10-a7e0-9cce499c5208</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.4.6" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OguzhanHocaEgitim.ServiceDefaults\OguzhanHocaEgitim.ServiceDefaults.csproj" />
      <ProjectReference Include="..\ServiceBusShared\ServiceBusShared.csproj" />
    </ItemGroup>
</Project>
