<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.1" />
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Applications\Applications.csproj" />
    <ProjectReference Include="..\Infrastructures\Infrastructures.csproj" />
    <ProjectReference Include="..\Persistences\Persistences.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
