@RabbitMQApp_API_HostAddress = http://localhost:5089



GET {{RabbitMQApp_API_HostAddress}}/send-with-no-ack
###
GET {{RabbitMQApp_API_HostAddress}}/send-with-ack

###
GET {{RabbitMQApp_API_HostAddress}}/send-with-dead-letter-exchange
